config/routes.rb
Rails.application.routes.draw do
  #  get 'translations/index'
  #  get 'translations/translate'
  #  post 'translations/translate', as: :translate
  get 'sessions/new'
  
  root "static_pages#home"
  get  "/help",    to: "static_pages#help"
  get  "/about",   to: "static_pages#about"
  get  "/contact", to: "static_pages#contact"
  get  "static_pages/translate", to: "static_pages#translate"
  post 'static_pages/translate', as: :translate
  get  "/signup", to: "users#new"
  get    "/login",   to: "sessions#new"
  post   "/login",   to: "sessions#create"
  delete "/logout",  to: "sessions#destroy"
  resources :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def about
  end

  def contact
  end
 #------------------------------------------------------------------------------------
#  def index
#  end

#  before_action :set_defaults
#  def translate_params
#    params.permit(:source, :source_language, :destination_language)
#  end

#  def translate
#    @source = translate_params[:source]
#    @source_language = translate_params[:source_language]
#    @destination_language = translate_params[:destination_language]
#    body = {
#      q: @source,
#      target: @destination_language.upcase
#    }
#    body[:source] = @source_language.downcase unless @source_language.empty?
#    translation = api_request(
#      'language/translate/v2',
#      method: :post,
#      body: URI.encode_www_form(body)
#    )
#    @translation = translation['data']['translations'].first['translatedText']
#    render action: :index
#  end


#  private
#  def set_defaults
#    @languages = fetch_languages
#  end
#  def api_request(path, method: :get, body: nil)
#    params = {
#      headers: {
#        'x-rapidapi-key': '102af2a43cmshb712411545b21b3p121e3cjsn0cc724e8fb83',
#        'content-type': 'application/x-www-form-urlencoded'
#      }
#    }
#    params[:body] = body if body
#    response = Excon.send(method,
#      "https://google-translate1.p.rapidapi.com/#{path}",
#      params
#    )
#    JSON.parse(response.body)
#  end
#  def fetch_languages
#    languages = api_request('language/translate/v2/languages')
#    keys = languages['data']['languages'].map { |l| l['language'].upcase }
#    I18nData
#      .languages
#      .slice(*keys)
#      .each_with_object([]) do |(iso, name), memo|
#        memo << [name, iso]
#      end
#  end

#-------------------------------------------------------------------------------------

end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>

    <h1>About</h1>
    <p>
      The <a href="https://www.railstutorial.org/"><em>Ruby on Rails
      Tutorial</em></a>, part of the
      <a href="https://www.learnenough.com/">Learn Enough</a> family of
      tutorials, is a
      <a href="https://www.railstutorial.org/book">book</a> and
      <a href="https://screencasts.railstutorial.org/">screencast series</a>
      to teach web development with
      <a href="https://rubyonrails.org/">Ruby on Rails</a>.
      This is the sample app for the tutorial.
    </p>
  

app/views/static_pages/contact.html.erb
<% provide(:title, "Contact") %>

<h1>Contact</h1>
<p>
  Contact the Ruby on Rails Tutorial about the sample app at the
  <a href="https://www.railstutorial.org/contact">contact page</a>.
</p>

app/views/static_pages/help.html.erb
<% provide(:title, "Help") %>

    <h1>Help</h1>
    <p>
      Get help on the Ruby on Rails Tutorial at the
      <a href="https://www.railstutorial.org/help">Rails Tutorial help
      page</a>.
      To get help on this sample app, see the
      <a href="https://www.railstutorial.org/book"><em>Ruby on Rails
      Tutorial</em> book</a>.
    </p>

app/views/static_pages/home.html.erb
<div class="center jumbotron">
  <h1>Welcome to the Sample App</h1>

  <h2>
    This is the home page for the
    <a href="https://www.railstutorial.org/">Ruby on Rails Tutorial</a>
    sample application.
  </h2>

  <%= link_to "Sign up now!", signup_path , class: "btn btn-lg btn-primary" %>
</div>

<%= link_to image_tag("rails.svg", alt: "Rails logo", width: "200"),
                      "https://rubyonrails.org/" %>

app/views/static_pages/trans.html.erb
<% provide(:title, "Translate") %>

<div class="container">
  <h1 class="text-center">Translator</h1>

  <%= form_with url: translate_path, method: :post, local: true do %>
    <div class="row">
        <div class="col-lg-5">
          <div class="form-group">
            <label for="source">Translate</label>
            <%= text_area_tag :source, @source, class: 'form-control', style: 'width: 100%; height: 100px' %>
          </div>

          <div class="form-group">
            <label for="source_language">From</label>

            <%# <%= select_tag :source_language, options_for_select(@languages, @source_language), class: 'form-control', include_blank: 'Auto-detect' %> %>
          </div>
        </div>

        <div class="col-lg-2 d-flex align-items-center justify-content-center">
          <button type="submit" class="btn btn-primary">
            Translate <i class="fa fa-arrow-right"></i>
          </button>
        </div>

        <div class="col-lg-5">
          <div class="form-group">
            <label for="translate">Translation</label>
            <%= text_area_tag :translate, @translate, class: 'form-control', style: 'width: 100%; height: 100px', readonly: true %>
          </div>

          <div class="form-group">
            <label for="destination_language">To</label>

            <%# <%= select_tag :destination_language, options_for_select(@languages, @destination_language), class: 'form-control' %> %>
          </div>
        </div>
    </div>
  <% end %>
</div>

app/views/static_pages/translate.html.erb
<% provide(:title, "Translate") %>

<div class="container">
  <h1 class="text-center">Translator</h1>

  <%= form_with url: translate_path, method: :post, local: true do %>
    <div class="row">
        <div class="col-lg-5">
          <div class="form-group">
            <label for="source">Translate</label>
            <%= text_area_tag :source, @source, class: 'form-control', style: 'width: 100%; height: 100px' %>
          </div>

          <div class="form-group">
            <label for="source_language">From</label>

            <%# <%= select_tag :source_language, options_for_select(@languages, @source_language), class: 'form-control', include_blank: 'Auto-detect' %> %>
          </div>
        </div>

        <div class="col-lg-2 d-flex align-items-center justify-content-center">
          <button type="submit" class="btn btn-primary">
            Translate <i class="fa fa-arrow-right"></i>
          </button>
        </div>

        <div class="col-lg-5">
          <div class="form-group">
            <label for="translate">Translation</label>
            <%= text_area_tag :translate, @translate, class: 'form-control', style: 'width: 100%; height: 100px', readonly: true %>
          </div>

          <div class="form-group">
            <label for="destination_language">To</label>

            <%# <%= select_tag :destination_language, options_for_select(@languages, @destination_language), class: 'form-control' %> %>
          </div>
        </div>
    </div>
  <% end %>
</div>